name: build

on:
  push:
    branches: [ main, apiv4 ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-2025
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v7

    - name: Setup .NET
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: |
          8.0.x
          9.0.x
          10.0.x

    - name: Remove ASP.NET sample
      run: dotnet sln serilog-sinks-elmahio.sln remove samples\Serilog.Sinks.ElmahIo.AspNet.Net48\Serilog.Sinks.ElmahIo.AspNet.Net48.csproj

    - name: Install dependencies
      run: dotnet restore

    - name: Check for vulnerable packages
      shell: bash
      run: |
        set -e # This will cause the script to exit on the first error
        OUTPUT=$(dotnet list src/Serilog.Sinks.ElmahIo/Serilog.Sinks.ElmahIo.csproj package --vulnerable)
        echo "$OUTPUT"
        if echo "$OUTPUT" | grep -q 'no vulnerable packages'; then
          echo "No vulnerable packages found"
        else
          if echo "$OUTPUT" | grep -q 'vulnerable'; then
            echo "Vulnerable packages found"
            exit 1
          fi
        fi

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Pack
      run: dotnet pack --configuration Release src/Serilog.Sinks.ElmahIo/Serilog.Sinks.ElmahIo.csproj /p:Version=6.0.${{ github.run_number }}-pre

    - name: Install dotnet-validate
      run: dotnet tool install --global dotnet-validate --version 0.0.1-preview.582

    - name: Validate
      run: dotnet validate package local src/Serilog.Sinks.ElmahIO/bin/Release/Serilog.Sinks.ElmahIo.6.0.${{ github.run_number }}-pre.nupkg

    - name: NuGet login (OIDC → temp API key)
      uses: NuGet/login@v1
      id: nuget-login
      with:
        user: ${{ secrets.NUGET_USER }}
      if: ${{ github.event_name == 'push' }}

    - name: Push
      run: dotnet nuget push src/Serilog.Sinks.ElmahIo/bin/Release/Serilog.Sinks.ElmahIo.6.0.${{ github.run_number }}-pre.nupkg --api-key ${{ steps.nuget-login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      if: ${{ github.event_name == 'push' }}

    # - name: Refresh Bugster
    #   uses: elmahio/actions/refresh-bugster-repository@v1.2
    #   with:
    #     signing: ${{ secrets.BUGSTER_SIGNING_KEY }}
    #     url: ${{ secrets.FUNCTION_APP_URL }}
    #     repository: ${{ github.event.repository.name }}
    #   if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}